Repository TacticsCH/WA-INN, pull requests merged in 2021-03, with the labels that each got.

#11 Feature/floorinn
  MonoSans.png
  inn0.json
Labels: Infrastructure 🚩, Mapping 🖼

#12 Feature/zones jitsi
  map.json
  maps/inn0.json
Labels: Infrastructure 🚩

#33 [test]Testé la faisabilité de créer un 'trou de verre' pour aller dan…
  maps/inn0.json
Labels: Meublage 🧱

#34 add: inn 13 desks
  maps/inn0.json
Labels: Meublage 🧱

#35 fix: jitsi zones
  maps/inn0.json
Labels: Configuration 🔧

#36 feature: add default furnitures to INN0's office
  maps/inn0.json
Labels: Meublage 🧱
